# Build customization
before:
  hooks:
    - go mod download
    - go generate github.com/iknite/raft-life/preset

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    binary: raft-life
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7
archive:
  format: binary

